#!/usr/bin/env bash

prefix="vcw_module_hkvb_confluent_schema_registry__$1"
prefix="vcw_module_hkvb_confluent_schema_registry__$1"

if [[ "vcw_module_hkvb_confluent_schema_registry__schema_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_confluent_schema_registry__schema_secrets_volume
fi
