#!/usr/bin/env bash

prefix="hkvb_confluent_schema_registry__$1"
prefix="hkvb_confluent_schema_registry__$1"

if [[ "hkvb_confluent_schema_registry__schema_registryz_schema_registry_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create hkvb_confluent_schema_registry__schema_registryz_schema_registry_secrets_volume
fi
