#!/usr/bin/env bash

prefix="hkvb_confluent_kafka_connect_sasl_traefik__$1"
prefix="hkvb_confluent_kafka_connect_sasl_traefik__$1"

if [[ "hkvb_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create hkvb_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_secrets_volume
fi

if [[ "hkvb_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_connect_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create hkvb_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_connect_secrets_volume
fi

if [[ "hkvb_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create hkvb_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_data_volume
fi

if [[ "hkvb_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_jars_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create hkvb_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_jars_volume
fi
