#!/usr/bin/env bash

prefix="hkvb_confluent_schema_registry_sasl_traefik__$1"
prefix="hkvb_confluent_schema_registry_sasl_traefik__$1"

if [[ "hkvb_confluent_schema_registry_sasl_traefik__schema_registry_nginx_config_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create hkvb_confluent_schema_registry_sasl_traefik__schema_registry_nginx_config_volume
fi

if [[ "hkvb_confluent_schema_registry_sasl_traefik__schema_registry_nginx_config_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v hkvb_confluent_schema_registry_sasl_traefik__schema_registry_nginx_config_volume:/vcw/pwd ${VCW_REGISTRY}hkvb/controlplane.vcw console cmd cp -r /source/hkvb/confluent/schema_registry/sasl/traefik/_module/volumes/schema_registry_nginx_config_volume/* /vcw/pwd
fi
