#!/usr/bin/env bash

prefix="vcw_module_hkvb_confluent_ksqldb__$1"
prefix="vcw_module_hkvb_confluent_ksqldb__$1"

if [[ "vcw_module_hkvb_confluent_ksqldb__ksqldb_ksqldb_queries_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_confluent_ksqldb__ksqldb_ksqldb_queries_volume
fi

if [[ "vcw_module_hkvb_confluent_ksqldb__ksqldb_ksqldb_queries_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcw_module_hkvb_confluent_ksqldb__ksqldb_ksqldb_queries_volume:/vcw/pwd ${VCW_REGISTRY}hkvb/controlplane.vcw console untar /source/hkvb/confluent_ksqldb/_module/volumes/ksqldb_ksqldb_queries_volume.tar
fi
