#!/usr/bin/env bash

prefix="vcw_module_hkvb_confluent_ksqldb__$1"
prefix="vcw_module_hkvb_confluent_ksqldb__$1"

if [[ "vcw_module_hkvb_confluent_ksqldb__ksqldb_queries_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_confluent_ksqldb__ksqldb_queries_volume
fi

if [[ "vcw_module_hkvb_confluent_ksqldb__ksqldb_queries_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_infometis_repos:/source -v vcw_module_hkvb_confluent_ksqldb__ksqldb_queries_volume:/vcw/queries ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/confluent/ksqldb/_module/volumes/ksqldb_queries_volume/* /vcw/queries
fi
