---
version: '3'
services:

# START SERVICE hkvb/nginx/rewrite
  nginx:
    image: ${VCW_REGISTRY}hkvb/nginx.base:1.19.3
    environment: ['VCW_STACK_NGINX_CONF_LOCATION=${KSQLDB_REST_ENVIRONMENT_CONF_PATH}', 'VCW_STACK_NGINX_CONF_PROXY_PASS=${KSQLDB_REST_ENVIRONMENT_CONF_UPSTREAM}']
    command: []
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_nginx_config_volume:/vcw/pwd']
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay, ${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${KSQLDB_REST_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${KSQLDB_REST_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${KSQLDB_REST_COMPOSE_EXTENSIONS}
# END SERVICE hkvb/nginx/rewrite

networks: {${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay: { external: true }, ${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_nginx_config_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
