#!/usr/bin/env bash

prefix="vcw_module_hkvb_confluent_kafka_connect_rest__$1"
prefix="vcw_module_hkvb_confluent_kafka_connect_rest__$1"

if [[ "vcw_module_hkvb_confluent_kafka_connect_rest__rest_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_confluent_kafka_connect_rest__rest_data_volume
fi
