#!/usr/bin/env bash

prefix="vcw_module_hkvb_confluent_ksqldb_sasl_traefik__$1"
prefix="vcw_module_hkvb_confluent_ksqldb_sasl_traefik__$1"

executionplane --silent docker container prune --force

if [[ "vcw_module_hkvb_confluent_ksqldb_sasl_traefik__ksqldb_nginx_config_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_hkvb_confluent_ksqldb_sasl_traefik__ksqldb_nginx_config_volume"
		result=$(docker volume ls | grep "vcw_module_hkvb_confluent_ksqldb_sasl_traefik__ksqldb_nginx_config_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcw_module_hkvb_confluent_ksqldb_sasl_traefik__ksqldb_ksql_server_queries_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcw_module_hkvb_confluent_ksqldb_sasl_traefik__ksqldb_ksql_server_queries_volume"
		result=$(docker volume ls | grep "vcw_module_hkvb_confluent_ksqldb_sasl_traefik__ksqldb_ksql_server_queries_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
