#!/usr/bin/env bash

prefix="vcw_module_hkvb_confluent_zookeeper__$1"
prefix="vcw_module_hkvb_confluent_zookeeper__$1"

if [[ "vcw_module_hkvb_confluent_zookeeper__module_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_confluent_zookeeper__module_secrets_volume
fi

if [[ "vcw_module_hkvb_confluent_zookeeper__module_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_confluent_zookeeper__module_data_volume
fi

if [[ "vcw_module_hkvb_confluent_zookeeper__module_log_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_confluent_zookeeper__module_log_volume
fi
