#!/usr/bin/env bash

# START CONFIGURATION
DOLLAR='$'
export VCW_MODULE_PACKAGES="\
schema_registry:hkvb/confluent/schema_registry/traefik"
# END CONFIGURATION

# START OTHER SETTINGS
# END OTHER SETTINGS

