#!/usr/bin/env bash

prefix="hkvb_confluent_schema_registry_traefik__$1"
prefix="hkvb_confluent_schema_registry_traefik__$1"

executionplane --silent docker container prune --force

if [[ "hkvb_confluent_schema_registry_traefik__schema_registry_nginx_config_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "hkvb_confluent_schema_registry_traefik__schema_registry_nginx_config_volume"
		result=$(docker volume ls | grep "hkvb_confluent_schema_registry_traefik__schema_registry_nginx_config_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
