---
version: '3'
services:

# START SERVICE hkvb/confluent/kafka_connect/rest
  kafka_connect_rest:
    image: ${VCW_REGISTRY}hkvb/confluent.kafka_connect.rest:6.1.1
    environment: ['VCW_STACK_STATIC_REST_BASE_API_LOGGING=${REST_ENVIRONMENT_REST_BASE_CURL_LOGGING}','REST_BASE_PROTOCOL=${REST_ENVIRONMENT_REST_KAFKA_CONNECT_PROTOCOL}','REST_BASE_HOST=${REST_ENVIRONMENT_REST_KAFKA_CONNECT_HOST}','REST_BASE_PORT=${REST_ENVIRONMENT_REST_KAFKA_CONNECT_PORT}','REST_BASE_URLPREFIX=${REST_ENVIRONMENT_REST_KAFKA_CONNECT_PREFIX}']
    command: [${REST_COMMAND}]
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_data_volume:/conteco/pwd'${REST_VOLUMES_MAPPINGS}]
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${REST_DEPLOY_MODE}
      resources:
        limits:
          memory: '${REST_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${REST_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      restart_policy: { condition: none }
${REST_COMPOSE_EXTENSIONS}
# END SERVICE hkvb/confluent/kafka_connect/rest

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_data_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
